/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "eu._4fh.WowDiscordSync"

sourceControl {
    gitRepository(uri("https://github.com/FH3095/abstract-bnet-api.git")) {
        producesModule("eu.4fh:abstract-bnet-api")
    }
}
